# Inspire by https://github.com/apache/impala/blob/master/cmake_modules/FindKerberos.cmake

# Find native krb5 includes and library
#
#  KRB5_INCLUDE_DIR - krb5.h include diretory
#  KRB5_LIBRARIE   - List of libraries when using krb5
#  KRB5_FOUND       - True

FIND_PATH(KRB5_INCLUDE_DIR krb5.h REQUIRED)

SET(KRB5_NAMES krb5 k5crypto com_err)
FIND_LIBRARY(KRB5_LIBRARIE NAMES ${KRB5_NAMES} REQUIRED)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Krb5 REQUIRED_VARS KRB5_LIBRARIE KRB5_INCLUDE_DIR)
MARK_AS_ADVANCED(KRB5_LIBRARIE KRB5_INCLUDE_DIR)

IF(Krb5_FOUND AND NOT TARGET Krb5::Krb5)
  ADD_LIBRARY(Krb5::Krb5 UNKNOWN IMPORTED)
  SET_TARGET_PROPERTIES(Krb5::Krb5 PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${KRB5_INCLUDE_DIR}")
  SET_PROPERTY(TARGET Krb5::Krb5 APPEND PROPERTY IMPORTED_LOCATION "${KRB5_LIBRARIE}")
endif()
