# Find native krb5 includes and library
#
#  KRB5_INCLUDE_DIR - krb5.h diretory.
#  KRB5_LIBRARIES   - List of libraries when using krb5.
#  KRB5_FOUND       - True.

# FIND_PATH(KRB5_INCLUDE_DIR krb5.h)
# MESSAGE(KRB5_INCLUDE_DIR: ${KRB5_INCLUDE_DIR})

# SET(KRB5_NAMES krb5 k5crypto com_err)
# FIND_LIBRARY(KRB5_LIBRARIES NAMES ${KRB5_NAMES})
# MESSAGE(KRB5_LIBRARIES: ${KRB5_LIBRARIES})

# INCLUDE(FindPackageHandleStandardArgs)
# FIND_PACKAGE_HANDLE_STANDARD_ARGS(Krb5 DEFAULT_MSG KRB5_LIBRARIES KRB5_INCLUDE_DIR)

# MARK_AS_ADVANCED(KRB5_LIBRARIES KRB5_INCLUDE_DIR)
